# .travis.yml
---

dist: trusty
sudo: required
language: python
python:
  - "2.7"
  - "3.6"
env:
  - >
    DISTRIBUTION=ubuntu-upstart
    DIST_VERSION=14.04
    MONGODB_VERSION=3.4
  - >
    DISTRIBUTION=ubuntu-upstart
    DIST_VERSION=14.04
    MONGODB_VERSION=3.2
  - >
    DISTRIBUTION=centos
    DIST_VERSION=6-builded
    MONGODB_VERSION=3.2
  - >
    DISTRIBUTION=centos
    DIST_VERSION=6-builded
    MONGODB_VERSION=3.4
  - >
    DISTRIBUTION=centos
    DIST_VERSION=7-builded
    MONGODB_VERSION=3.2
  - >
    DISTRIBUTION=centos
    DIST_VERSION=7-builded
    MONGODB_VERSION=3.4
#  - >
#    distribution=debian
#    version=7

services:
  - docker

install:
  - bash tests/scripts/before_install.sh

script:
  - bash tests/scripts/test.sh
