---

- name: Install required package for mongodb_user module
  apt: name=python-pymongo

- name: create administrative user siteRootAdmin
  mongodb_user: 
    database: admin
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    login_host: "{{ mongodb_user_login_host|default('localhost') }}"
  with_items:
    - { 
      name: siteRootAdmin, 
      password: "{{ mongodb_root_admin_password }}",
      roles: "root"
      }

- name: create administrative user siteUserAdmin
  mongodb_user: 
    database: admin
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    login_host: "{{ mongodb_user_login_host|default('localhost') }}"
    login_user: "siteRootAdmin"
    login_password: "{{ mongodb_root_admin_password }}"
  with_items:
    - { 
      name: siteUserAdmin,
      password: "{{ mongodb_user_admin_password }}",
      roles: "userAdminAnyDatabase"
      }

- name: create normal users
  mongodb_user:
    database: "{{ item.database }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    roles: "{{ item.roles }}"
    login_host: "{{ mongodb_user_login_host|default('localhost') }}"
    login_user: "siteRootAdmin"
    login_password: "{{ mongodb_root_admin_password }}"
  with_items:
    - {{ mongodb_users }}
  when: mongodb_users is defined
