---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: configure.yml

- name: Ensure mongodb is started
  service: name=mongod state=started enabled=yes
  changed_when: False
