---

- name: Replication configuration
  mongodb_replication:
    login_host: "{{ mongodb_login_host |default('localhost') }}"
    login_port: "{{ mongodb_login_port|default(27017) }}"
    login_user: "{{ mongodb_root_admin_name }}"
    login_password: "{{ mongodb_root_admin_password }}"
    replica_set: "{{ mongodb_conf_replSet }}"
    host_name: "{{ item.host_name }}"
    host_port: "{{ item.host_port }}"
    host_type: "{{ item.host_type|default('replica') }}"
  when: mongodb_conf_auth == "yes" and mongodb_replication_hosts is defined
  register: mongodb_replication_status
  with_items:
    - "{{ mongodb_replication_params }}"
